version: "3"
services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      TZ: "UTC"
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
