app:
  env: local
  log_level: debug
  name: api
  url: http://localhost:3000
  allow_origins: http://localhost:3001
  auth_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxx
db:
  user: root
  password: root
  host: localhost
  name: local
  port: 5432
