// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/smochii/go-clean-architecture/handler"
	"github.com/smochii/go-clean-architecture/infrastructure/database"
	"github.com/smochii/go-clean-architecture/route"
	"github.com/smochii/go-clean-architecture/service"
)

// Injectors from wire.go:

func Route() *route.Route {
	db := database.NewConnection()
	userRepository := database.NewUserRepository(db)
	iUserService := service.NewUserService(userRepository)
	middlewareHandler := handler.NewMiddlewareHandler(iUserService)
	iAuthService := service.NewAuthService(userRepository)
	authHandler := handler.NewAuthHandler(iAuthService)
	userHandler := handler.NewUserHandler(iUserService)
	routeRoute := route.NewRoute(middlewareHandler, authHandler, userHandler)
	return routeRoute
}

// wire.go:

var providerSet = wire.NewSet(database.NewConnection, database.NewUserRepository, service.NewUserService, service.NewAuthService, handler.NewMiddlewareHandler, handler.NewAuthHandler, handler.NewUserHandler)
